version: '3.8'

services:
  fastmcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount your server implementation
      - ./src:/app/src:ro
    restart: unless-stopped
    
  # Development service with hot reload
  fastmcp-dev:
    build: .
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: ["pnpm", "dev"]
    restart: unless-stopped
    profiles:
      - dev